#!/bin/dash


#checks if .legit directory exists already
if [ ls -a -d '.legit' ]
then
    echo "legit-init: error: .legit already exists"
    exit 0
fi

#creates legit directories and log
mkdir .legit
mkdir .legit/index
mkdir .legit/commits
echo "" > .legit/log.txt

echo "Initialized empty legit repository in .legit"

exit 1
