#!/bin/dash



#checks legit repository and log exists
if [ ls -a -f '.legit/log.txt' ]
then
    :
    else
    echo legit-log: error: no .legit directory containing legit repository exists
    exit
fi



#eliminates empty lines, prints log
sed -i '/^$/d' .legit/log.txt
cat .legit/log.txt
